apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  namespace: c3-project
spec:
  selector:
    app: udagram-api-feed
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080